//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCYorbitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelationShip
    {
        public int ID { get; set; }
        public Nullable<int> MemberId { get; set; }
        public string RelatedMemberId { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string RelationType { get; set; }
        public Nullable<System.DateTime> CreatedTimeStamp { get; set; }
        public Nullable<System.DateTime> LastModifiedTimeStamp { get; set; }
        public Nullable<int> MetaActive { get; set; }
        public string ApplicationID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual AddMember AddMember { get; set; }
    }
}
